version: '2.0'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  web:
    extends:
      file: docker-compose-base.yml
      service: rails
    command: 'rails server'
    depends_on:
      - db
    ports:
      - 3000:3000

  jobs_work:
    extends:
      file: docker-compose-base.yml
      service: rails
    command: 'rake jobs:work'
    depends_on:
      - db

volumes:
  db:
  bundle:
