version: '2.0'

services:
  rails:
    image: instedd/nginx-rails:2.0
    environment:
      RAILS_ENV:
      DATABASE_HOST: 'db'
    pid: host
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
