version: '2.0'

services:
  db:
    image: mysql:5.6
    platform: linux/amd64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  web: &rails
    image: instedd/nginx-rails:2.0
    platform: linux/amd64
    environment:
      RAILS_ENV:
      DATABASE_HOST: 'db'
    pid: host
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
    command: 'rails server'
    ports:
      - 3000:3000

  jobs_work:
    <<: *rails
    command: 'rake jobs:work'
    ports: []

volumes:
  db:
  bundle:
