#DO NOT MODIFY! AUTOMATICALLY GENERATED FILE!
_('channel')
_('Channel|Name')
_('Channel|Address')
_('log')
_('Log|Severity')
_('Log|Description')
_('message')
_('Message|Text')
_('Message|Offset')
_('Message|Occurrence rule')
_('schedule')
_('Schedule|Keyword')
_('Schedule|Timescale')
_('Schedule|Welcome message')
_('Schedule|Title')
_('Schedule|Paused')
_('subscriber')
_('Subscriber|Phone number')
_('Subscriber|Subscribed at')
_('Subscriber|Offset')
_('user')
_('User|Email')
_('User|Encrypted password')
_('User|Reset password token')
_('User|Reset password sent at')
_('User|Remember created at')
_('User|Sign in count')
_('User|Current sign in at')
_('User|Last sign in at')
_('User|Current sign in ip')
_('User|Last sign in ip')
_('User|Confirmation token')
_('User|Confirmed at')
_('User|Confirmation sent at')
_('User|Lang')
#DO NOT MODIFY! AUTOMATICALLY GENERATED FILE!

# Hardcoded strings which failed to be obtained by the gettext find all script
_("Title")
_("Welcome message")
_("Timescale")
_("This Reminder is paused and won't send messages.")
_("This Reminder is active and will be sending messages to registered users.")
_("Random Once")
_("Write your welcome message here")
_("Add message")
_("Choose whether you want to set up a timeline for your messages or send them randomly")
_("(Only available if there are no subscribers)")
_("an hour")
_("a day")
_("a week")
_("a month")
_("a year")
_("Hour")
_("Day")
_("Week")
_("Month")
_("Year")
_("Reset it")
_("Email")
_("Password")
_("Remember me")
_("http://instedd.org/technologies/")
_("http://instedd.org/technologies/nuntium/")
_("New password")
_("Confirm new password")
_("Current password")
_("Delete my account")
_("Are you sure?")
_('Change channel')
_('learn More')
_('Show All')
_('Paused')
_('Running')
_('Finish')
_('Password confirmation')
_('errors')
_('Information')
_('Error')
_('Warning')